on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: published-app
        path: ./publish

  deploy:
    needs: build  # Ensures deploy only runs if build is successful
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # download artifacts
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with: 
        name: published-app
        path: ./publish

    # Configure AWS credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Upload artifacts to S3
    - name: Upload to S3
      run: aws s3 cp ./publish s3://frontendsolutionbucket/ --recursive
